# Generated by Django 4.1.7 on 2023-03-31 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='regdno',
        ),
    ]
